Part1 category mapping
Tuomas-Unit8/Clockify-API-Tool pull request #2
Opened 2022-03-25 10:03 UTC by Tuomas-Unit8

- removed most hardcoded variables
- added a json file containing fields for Clockify categories/projects (our DataFrame fields), containing each the mappings, with a bit indicating whether the field of the DataFrame should be contained in the mapping list.

2022-03-29 12:53 UTC, Seb-Unit8 requested changes
Good practice here is also to go through each comment and mark them as resolved when you have done them for the reviewer :)

2022-03-29 12:53 UTC, Seb-Unit8 commented on environment.yml
> +name: clockify_api_env
For this one can you please use the channels above, and remove the final prefix line. 

For the requirements list, the goal is to have as minimal as possible for mamba/conda to resolve the environment with the most up to date packages possible for the given constraints. Therefore, simply set something like:
```
dependencies:
  - python=3.10
  - pip=21.2.4
  - pandas=1.4.1
```
an any other packages you `mamba install`ed.

2022-03-30 06:30 UTC, Tuomas-Unit8 commented on categories_projects_gen.py
>      df = df.drop_duplicates(subset=["Project"])
This was the case in a previous commit (and indeed dropped a "Other" project), now the subset is ["Project", "Client"]

2022-03-30 06:43 UTC, Tuomas-Unit8 commented on categories_projects_gen.py
>      ooo_substring = "OOO - "
Good catch, it seemed to work without issues but it's always better to be sure, so I changed this

2022-03-30 06:57 UTC, Tuomas-Unit8 commented on environment.yml
> +name: clockify_api_env
Thank you for the example, it made it more understandable, I had generated the environment file from the current environment (which had automatically installed way too many packages during pandas installation), which visibly should not be done (due to the prefixes etc.), it is now fixed. I just left the requests package to make it easier, since it will be used in the next part.

2022-03-31 11:35 UTC, Seb-Unit8 requested changes
Last little one and we can get this merged!

2022-03-31 11:35 UTC, Seb-Unit8 commented on environment.yml
> +  - pandas>=1.4.1
One last one that I learned from expirience- fix the library versions with `=` as tempting as `>=` is. Things will usually break in a couple of month with `>=` requirements with package updates.

2022-03-31 11:53 UTC, Seb-Unit8 commented on categories_projects_gen.py
>      df = pd.read_csv("Clockify_summary_lastyear.csv")
Actually also just thinking how to modularise this:

I think rename the function and make the signature

`def map_report_categories(df_filepath, json_mappings: dict ) -> : pd.DataFrame`

and we have

```
if __name__ == "__main__":
    with open("category_mapping.json") as f:
        json_map = json.load(f)
    summarise_report_categories("Clockify_summary_lastyear.csv", json_map) 
```

and `add_default_mappings` is renamed to `add_mappings`

2022-03-31 12:13 UTC, Seb-Unit8 commented on categories_projects_gen.py
>      df.rename(columns={"Client": "Clockify Category"}, inplace=True)
Also this line is throwing a warning `SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame`.

Seeing as you have been doing `df = df.{function}` for most of the program instead of inplace, might be better to stick to that and remove the `inplace` arg.

2022-03-31 12:15 UTC, Tuomas-Unit8 commented on categories_projects_gen.py
>      df.rename(columns={"Client": "Clockify Category"}, inplace=True)
thanks for the catch!

2022-03-31 12:40 UTC, Seb-Unit8 approved these changes

2022-03-31 12:53 UTC, merged