Part2 join userdata, start grouping mappings and counting working hours/holidays
Tuomas-Unit8/Clockify-API-Tool pull request #3
Opened 2022-03-31 14:36 UTC by Tuomas-Unit8

add functions to:
- gather timesheets
- join timesheets (amount of hours) with {project | client} pairs (represented by projectId)
- group the joined DataFrame by default mapping (get hours per mapping)
- get amount of holidays
- get amount of worked hours
- (and other helper functions for all the above)

2022-04-01 19:11 UTC, Seb-Unit8 commented
Probably a good time for two things:

1. Have a read of [PEP8](https://peps.python.org/pep-0008/). Absolutely not a religious text as some people pretend it is, but a good starting point to understand practical python
2. Look at [black](https://black.readthedocs.io/en/stable/). If you can get [this working](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) without too much trouble I would also suggest doing do. By my reckoning, the black standards are really excellent.

2022-04-01 20:03 UTC, Seb-Unit8 requested changes

2022-04-01 20:03 UTC, Seb-Unit8 commented on userdata_join_mapping.py
> +    df_mappings_projectids = get_df_mappings_projectids(url, workspaceId, headers, params, df_mappings)
Let's have a sit down on Monday for 15 minutes and have a look at how this runs with an API key, I realise now I explained the idea of the merge poorly. Creating an id like this is a bit of a crutch, because you may have far more columns acting as a fingerprint (or non string, etc).

My intention was that we leave the clockify `project` and `catagory` as two seperate columns in all data structures. When we do dataframe [`merge`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html) or [`groupby`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html) (which would be followed by `agg`) the `on`/`by` parameter is a list of these two columns.

2022-04-04 06:33 UTC, Tuomas-Unit8 commented on userdata_join_mapping.py
> +# these 2 functions could be combined into 1, but maybe clearer as separate ones?
good catch for scalability, thank you!

2022-04-04 08:13 UTC, Seb-Unit8 approved these changes

2022-04-04 09:03 UTC, merged